---
apiVersion: v1
kind: Namespace
metadata:
  name: app-etherpad
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: app-etherpad
  namespace: app-etherpad
spec:
  type: Git
  pathname: https://github.com/lcolagio/rhacm-workshop.git
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: app-etherpad
  namespace: app-etherpad
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - app-etherpad
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: app-etherpad
  namespace: app-etherpad
  labels:
    app: app-etherpad
  annotations:
    apps.open-cluster-management.io/github-path: 03.application-lifecycle/demo-application-git-etherpad/app-resources
spec:
  channel: app-etherpad/app-etherpad
  placement:
    placementRef:
      kind: PlacementRule
      name: dev-clusters
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: dev-clusters
  namespace: app-etherpad
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      environment: dev
