---
apiVersion: v1
kind: Namespace
metadata:
  name: app-wordpress-ns
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: app-wordpress
  namespace: app-wordpress-ns
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - app-wordpress
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: bitnami
  namespace: app-wordpress-ns
spec:
  pathname: https://charts.bitnami.com/bitnami
  type: HelmRepo
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: app-wordpress
  name: app-wordpress-placement-1
  namespace: app-wordpress-ns
spec:
  clusterSelector:
    matchLabels:
      environment: dev
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  labels:
    app: app-wordpress
  name: app-wordpress-subscription-1
  namespace: app-wordpress-ns
spec:
  channel: app-wordpress-ns/bitnami
  name: wordpress
  packageOverrides:
    - packageAlias: wordpress
      packageName: wordpress
  placement:
    placementRef:
      kind: PlacementRule
      name: app-wordpress-placement-1



