apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-a
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    name: cluster-a
    server: '*'
  sourceRepos:
  - '*'