---
apiVersion: v1
kind: Namespace
metadata:
  name: app-node-js-ex-k-ns
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: helm-redhat
  namespace:  app-node-js-ex-k-ns
spec:
  type: HelmRepo
  pathname: https://redhat-developer.github.io/redhat-helm-charts
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: dev-clusters
  namespace:  app-node-js-ex-k-ns
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      environment: dev
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  namespace:  app-node-js-ex-k-ns
  name:  app-node-js-ex-k
#  annotations:
#    apps.open-cluster-management.io/deployables: ''
#  selfLink: /apis/app.k8s.io/v1beta1/namespaces/php/applications/ app-node-js-ex-k
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          -  app-node-js-ex-k
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  namespace:  app-node-js-ex-k-ns
  name:  app-node-js-ex-k-subscription-1
  annotations: {}
  labels:
    app:  app-node-js-ex-k
spec:
  name: example-node-js-ex-k
  channel:  app-node-js-ex-k-ns/helm-redhat
  packageOverrides:
    - packageAlias: node-js-ex-k
      packageName: node-js-ex-k
  placement:
    placementRef:
      name: dev-clusters
      kind: PlacementRule
---





